### ISSUE TITLE
English

### ISSUE THREAD

**Issue by clintonyeb** [jawil/blog#12]
Is there a way for an English explaining what's going on?

**Comment by jawil** [comment]
No,but you can use Google translation.
Sharp tools make good work.

**Comment by tunnckoCore** [comment]
why the hell this continues to get top places at Trending?!

**Comment by clintonyeb** [comment]
People have a great taste for crazy stuff. Try running the code. I was surprised too

**Comment by clintonyeb** [comment]
Or let's say, the guy has a lot of friends or he's popular :thinking:

**Comment by jawil** [comment]
Where did you see my blog? Can you give a link?   @clintonyeb  @tunnckoCore 
You can visit this site to understand me?[Please click me](https://juejin.im/timeline) or enter 
 https://juejin.im/timeline

**Comment by clintonyeb** [comment]
https://github.com/trending/javascript There you are. Top 10 trending GitHub repositories!!

**Comment by jawil** [comment]
Thanks ! 
If you wan to understand this gelivable blog,you should learn a little Chinese.😄
Welcome to China,my github visitor! 
@clintonyeb

**Comment by clintonyeb** [comment]
Can you speak a little english??

**Comment by clintonyeb** [comment]
`
let me = ([][[]]+[])[+!![]]+([]+{})[!+[]+!![]]
console.log(me); // -> nb
`

Is blowing my mind away!

**Comment by jawil** [comment]
you can read this article ->[click me](https://github.com/jawil/blog/issues/5) to understand this result.

If you don't understand chinese,you can ask  your friend who is good at chinese for  translating this article into english.😄 

@clintonyeb

**Comment by clintonyeb** [comment]
Yes, I have some friends. Thanks... :smile:

**Comment by jawil** [comment]
Also,You can find the answer from this website.->[click me](http://stackoverflow.com/)

This is very a great website,but my english is just so so.

We also have similar website in China.->[click me](https://segmentfault.com/questions)

@clintonyeb

**Comment by lishuo9527** [comment]
shuang ji 666
