### ISSUE TITLE
3 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49  #-------------------------------------------------  #  # Project created by QtCreator 2018-10-25T08:32:36  #  #-------------------------------------------------   QT       += core gui QT       += serialport  greaterThan(QT_MAJOR_VERSION, 4): QT += widgets  TARGET = COMTOOLV2 TEMPLATE = app RC_FILE =main.rc  # The following define makes your compiler emit warnings if you use  # any feature of Qt which has been marked as deprecated (the exact warnings  # depend on your compiler). Please consult the documentation of the  # deprecated API in order to know how to port your code away from it.  DEFINES += QT_DEPRECATED_WARNINGS  # You can also make your code fail to compile if you use deprecated APIs.  # In order to do so, uncomment the following line.  # You can also select to disable deprecated APIs only up to a certain version of Qt.  #DEFINES += QT_DISABLS 

### ISSUE THREAD

**Issue by wefgy** [jawil/blog#35]
#-------------------------------------------------

#

# Project created by QtCreator 2018-10-25T08:32:36

#

#-------------------------------------------------

QT       += core gui
QT       += serialport

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = COMTOOLV2
TEMPLATE = app
RC_FILE =main.rc

# The following define makes your compiler emit warnings if you use

# any feature of Qt which has been marked as deprecated (the exact warnings

# depend on your compiler). Please consult the documentation of the

# deprecated API in order to know how to port your code away from it.

DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.

# In order to do so, uncomment the following line.

# You can also select to disable deprecated APIs only up to a certain version of Qt.

#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

CONFIG += c++11

SOURCES += \
        main.cpp \
        mainwindow.cpp \
    about.cpp

HEADERS += \
        mainwindow.h \
    hexascii.h \
    about.h

FORMS += \
        mainwindow.ui \
    about.ui

# Default rules for deployment.

qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    res.qrc

**Comment by wefgy** [comment]
怎么样？求帮助

**Comment by caogenyin** [comment]
just stupid
